### ISSUE TITLE
Make params optional on $ensure => false

### ISSUE THREAD

**Issue by martin-koerner** [TheMeier/themeier-systemd_cron#1]
When $ensure => false there should be no need to specify $on_calendar, $command and $service_description

Maybe it's also a good idea to support common values "present" and "absent" for the $ensure attribute (e.g. Optional[Enum['present', 'absent']] instead of Optional[Boolean].

**Comment by TheMeier** [comment]
I don't think its worth to make the code more complex for that. Especially if you define a resource with ensure => false you propably had it in you manifests with ensure => true beforehand.

I'd rather think about cleanly identyfiyng puppet generated systemd timers and purging all which are not in the catalogue.
