### ISSUE TITLE
slashes / are not allowed in title

### ISSUE THREAD

**Issue by trefzer** [TheMeier/themeier-systemd_cron#16]
if a slash in the title occurs, systemd::unit throws an error on name validation:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, assert_type(): expects a match for Systemd::Unit = Pattern[/^[^\/]+\.(service|socket|device|mount|automount|swap|target|path|timer|slice|scope)$/], 
.....

**Comment by TheMeier** [comment]
Interesting. I never thought about using slashes in resource titles.
